name: tmux
version: 2.1bump5
summary: tmux is a terminal multiplexer
description: |
  What is a terminal multiplexer?
  It lets you switch easily between several programs in one terminal,
  detach them (they keep running in the background) and reattach them to a different terminal.
  And do a lot more.
https://github.com/shawn111/tmux.snap

apps:
  tmux:
    command: ./bin/tmux

parts:
  tmux:
    plugin: autotools
    source: https://github.com/tmux/tmux.git
    source-type: git
    build-packages: [libevent-dev, libncurses5-dev, pkg-config]
    stage-packages: [libevent-2.0-5, libncurses5]
